//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateCatalog.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apartment()
        {
            this.Сontract = new HashSet<Сontract>();
        }
    
        public int ID { get; set; }
        public string adressApart { get; set; }
        public string apartmentNum { get; set; }
        public string apartmentType { get; set; }
        public Nullable<int> apartmentSquare { get; set; }
        public int numRooms { get; set; }
        public string apartmentCondition { get; set; }
        public int price { get; set; }
        public string apartmentInfo { get; set; }
        public string fullNameOwner { get; set; }
        public string telOwner { get; set; }
        public Nullable<int> IDPhotoCatalog { get; set; }
    
        public virtual PhotoCatalog PhotoCatalog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сontract> Сontract { get; set; }
    }
}
