//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateCatalog.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int ID { get; set; }
        public string telClient { get; set; }
        public Nullable<int> IDindividual { get; set; }
        public Nullable<int> IDcorporate { get; set; }
    
        public virtual CorporateClient CorporateClient { get; set; }
        public virtual IndividualClient IndividualClient { get; set; }
        public virtual Сontract Сontract { get; set; }
    }
}
