//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateCatalog.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorporateClient
    {
        public int ID { get; set; }
        public string nameCorporate { get; set; }
        public string adressCorporate { get; set; }
        public string INN { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
