//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateCatalog.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndividualClient
    {
        public int ID { get; set; }
        public string adressIndivid { get; set; }
        public string passportNum { get; set; }
        public System.DateTime dateClient { get; set; }
        public string fullNameClient { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
